.TH "Dewpsi::EventDispatcher" 3 "Fri Jun 26 2020" "Dewpsi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dewpsi::EventDispatcher \- Dispatches events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventDispatcher\fP (\fBEvent\fP &e)"
.br
.RI "Sets the event to be dispatched\&. "
.ti -1c
.RI "template<typename T , typename F > bool \fBDispatch\fP (const F &func)"
.br
.RI "Dispatches the event with function of type \fCT\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Dispatches events\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dewpsi from the source code\&.
