#ifndef DEWPSI_H
#define DEWPSI_H

/**
    @brief  Dewpsi engine public header.
    This header is meant for the client, in order to see
    all the functions and types generated by this engine.
*/

#include <dewpsi/timer.h>
#include <dewpsi/application.h>

#endif /* DEWPSI_H */

